import { UserFull } from '../types/types';

export const initialUserFull: UserFull = {
  avatar_url: 'avatar_url',
  bio: 'Bio',
  blog: 'www.example.com',
  company: 'Company',
  created_at: '1970-01-01',
  email: 'me@example.com',
  events_url: 'events_url',
  followers: -1,
  followers_url: 'followers_url',
  following: -1,
  following_url: 'following_url',
  gists_url: 'gists_url',
  gravatar_id: 'gravatar_id',
  hireable: false,
  html_url: 'html_url',
  id: -1,
  location: 'Location',
  login: 'login',
  name: 'Firstname Lastname',
  node_id: 'node_id',
  organizations_url: 'organizations_url',
  public_gists: -1,
  public_repos: -1,
  received_events_url: 'received_events_url',
  repos_url: 'repos_url',
  site_admin: false,
  starred_url: 'starred_url',
  subscriptions_url: 'subscribers_url',
  twitter_username: '@TwitterUser',
  type: 'type',
  updated_at: '1970-01-01',
  url: 'www.github.com/example'
};
