import { UserFull } from '../types/types';

export const initialUserFull: UserFull = {
  avatar_url: 'initial',
  bio: 'initial',
  blog: 'initial',
  company: 'initial',
  created_at: 'initial',
  email: 'initial',
  events_url: 'initial',
  followers: -1,
  followers_url: 'initial',
  following: -1,
  following_url: 'initial',
  gists_url: 'initial',
  gravatar_id: 'initial',
  hireable: false,
  html_url: 'initial',
  id: -1,
  location: 'initial',
  login: 'initial',
  name: 'initial',
  node_id: 'initial',
  organizations_url: 'initial',
  public_gists: -1,
  public_repos: -1,
  received_events_url: 'initial',
  repos_url: 'initial',
  site_admin: false,
  starred_url: 'initial',
  subscriptions_url: 'initial',
  twitter_username: 'initial',
  type: 'initial',
  updated_at: 'initial',
  url: 'initial'
};
